services:
  - type: web
    name: location-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
